#!name=Spotify去广告
#!desc=Spotify去广告加部分解锁会员功能,音质不能设置为超高
#!icon=https://img.icons8.com/?size=100&id=ZuQiaFCa1vXe&format=png&color=000000
#!date=260404

[Header Rewrite]
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize header-del 'if-none-match'

[Map Local]
^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/pendragon\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

#客户端上报用户消耗行为
^https:\/\/.*-spclient\.spotify\.com(:443)?\/capping-api\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

#^https:\/\/.*-spclient\.spotify\.com(:443)?\/offline reject-dict
^https:\/\/.*-spclient\.spotify\.com(:443)?\/partner- data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/.*-spclient\.spotify\.com(:443)?\/pam-view-service\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

#屏蔽AI DJ的url
37i9dQZF1EYkqdzj48dyYq data-type=text data="{}" status-code=200 header="Content-Type:application/json"

#未知用途的404链接
^https:\/\/.*-spclient\.spotify\.com(:443)?\/social-connect\/v.\/sessions\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
spotify-gabo = type=http-request, pattern=^https:\/\/(.*-spclient\.spotify\.com(:443)?|spclient\.wg\.spotify\.com)\/gabo-receiver-service, script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-gabo.js, timeout=10

spotify-json = type=http-request, pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/, script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-Json-copy.js, timeout=10

spotifyProto = type=http-response, pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(\?.*)?$, script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-proto-eevee.js, requires-body=true, binary-body-mode=true, timeout=10

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

